package prototype.hibernate.datamodel.entities.product;
// Generated Oct 30, 2013 1:55:35 PM by Hibernate Tools 3.6.0



/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private int productId;
     private String productCode;
     private String productName;
     private String productImg;
     private String productDesc;
     private Double price;

    public Product() {
    }

	
    public Product(int productId) {
        this.productId = productId;
    }
    public Product(int productId, String productCode, String productName, String productImg, String productDesc, Double price) {
       this.productId = productId;
       this.productCode = productCode;
       this.productName = productName;
       this.productImg = productImg;
       this.productDesc = productDesc;
       this.price = price;
    }
   
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }
    public String getProductCode() {
        return this.productCode;
    }
    
    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public String getProductImg() {
        return this.productImg;
    }
    
    public void setProductImg(String productImg) {
        this.productImg = productImg;
    }
    public String getProductDesc() {
        return this.productDesc;
    }
    
    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }




}


