package prototype.hibernate.datamodel.entities.unit;
// Generated Oct 30, 2013 1:55:35 PM by Hibernate Tools 3.6.0



/**
 * Unit generated by hbm2java
 */
public class Unit  implements java.io.Serializable {


     private int unitId;
     private String unitName;

    public Unit() {
    }

	
    public Unit(int unitId) {
        this.unitId = unitId;
    }
    public Unit(int unitId, String unitName) {
       this.unitId = unitId;
       this.unitName = unitName;
    }
   
    public int getUnitId() {
        return this.unitId;
    }
    
    public void setUnitId(int unitId) {
        this.unitId = unitId;
    }
    public String getUnitName() {
        return this.unitName;
    }
    
    public void setUnitName(String unitName) {
        this.unitName = unitName;
    }




}


