package prototype.hibernate.datamodel.entities.inventory;
// Generated Oct 30, 2013 1:55:35 PM by Hibernate Tools 3.6.0



/**
 * InventoryDetail generated by hbm2java
 */
public class InventoryDetail  implements java.io.Serializable {


     private int inventoryDetailId;
     private Integer inventoryId;
     private Integer productId;
     private Double quantity;
     private Integer unitId;

    public InventoryDetail() {
    }

	
    public InventoryDetail(int inventoryDetailId) {
        this.inventoryDetailId = inventoryDetailId;
    }
    public InventoryDetail(int inventoryDetailId, Integer inventoryId, Integer productId, Double quantity, Integer unitId) {
       this.inventoryDetailId = inventoryDetailId;
       this.inventoryId = inventoryId;
       this.productId = productId;
       this.quantity = quantity;
       this.unitId = unitId;
    }
   
    public int getInventoryDetailId() {
        return this.inventoryDetailId;
    }
    
    public void setInventoryDetailId(int inventoryDetailId) {
        this.inventoryDetailId = inventoryDetailId;
    }
    public Integer getInventoryId() {
        return this.inventoryId;
    }
    
    public void setInventoryId(Integer inventoryId) {
        this.inventoryId = inventoryId;
    }
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
    public Double getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Double quantity) {
        this.quantity = quantity;
    }
    public Integer getUnitId() {
        return this.unitId;
    }
    
    public void setUnitId(Integer unitId) {
        this.unitId = unitId;
    }




}


