package prototype.hibernate.datamodel.entities.inventory;
// Generated Oct 30, 2013 1:55:35 PM by Hibernate Tools 3.6.0



/**
 * Inventory generated by hbm2java
 */
public class Inventory  implements java.io.Serializable {


     private int inventoryId;
     private String inventoryName;

    public Inventory() {
    }

	
    public Inventory(int inventoryId) {
        this.inventoryId = inventoryId;
    }
    public Inventory(int inventoryId, String inventoryName) {
       this.inventoryId = inventoryId;
       this.inventoryName = inventoryName;
    }
   
    public int getInventoryId() {
        return this.inventoryId;
    }
    
    public void setInventoryId(int inventoryId) {
        this.inventoryId = inventoryId;
    }
    public String getInventoryName() {
        return this.inventoryName;
    }
    
    public void setInventoryName(String inventoryName) {
        this.inventoryName = inventoryName;
    }




}


