package prototype.hibernate.datamodel.entities.inventory;
// Generated Oct 30, 2013 1:55:35 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * InventoryAdjustment generated by hbm2java
 */
public class InventoryAdjustment  implements java.io.Serializable {


     private int adjustmentId;
     private Integer inventoryId;
     private Integer productId;
     private Double quantityOld;
     private Double quantityNew;
     private Date date;
     private String comment;
     private String userName;

    public InventoryAdjustment() {
    }

	
    public InventoryAdjustment(int adjustmentId) {
        this.adjustmentId = adjustmentId;
    }
    public InventoryAdjustment(int adjustmentId, Integer inventoryId, Integer productId, Double quantityOld, Double quantityNew, Date date, String comment, String userName) {
       this.adjustmentId = adjustmentId;
       this.inventoryId = inventoryId;
       this.productId = productId;
       this.quantityOld = quantityOld;
       this.quantityNew = quantityNew;
       this.date = date;
       this.comment = comment;
       this.userName = userName;
    }
   
    public int getAdjustmentId() {
        return this.adjustmentId;
    }
    
    public void setAdjustmentId(int adjustmentId) {
        this.adjustmentId = adjustmentId;
    }
    public Integer getInventoryId() {
        return this.inventoryId;
    }
    
    public void setInventoryId(Integer inventoryId) {
        this.inventoryId = inventoryId;
    }
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
    public Double getQuantityOld() {
        return this.quantityOld;
    }
    
    public void setQuantityOld(Double quantityOld) {
        this.quantityOld = quantityOld;
    }
    public Double getQuantityNew() {
        return this.quantityNew;
    }
    
    public void setQuantityNew(Double quantityNew) {
        this.quantityNew = quantityNew;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }




}


