package prototype.hibernate.datamodel.entities.input;
// Generated Oct 30, 2013 1:55:35 PM by Hibernate Tools 3.6.0



/**
 * InputDetail generated by hbm2java
 */
public class InputDetail  implements java.io.Serializable {


     private int inputDetailId;
     private Integer inputId;
     private Integer productId;
     private String productName;
     private Double price;
     private Double quantity;
     private Integer unitId;
     private Integer inventoryId;
     private Double totalMoney;
     private Integer vendorId;
     private String vendorName;

    public InputDetail() {
    }

	
    public InputDetail(int inputDetailId) {
        this.inputDetailId = inputDetailId;
    }
    public InputDetail(int inputDetailId, Integer inputId, Integer productId, String productName, Double price, Double quantity, Integer unitId, Integer inventoryId, Double totalMoney, Integer vendorId, String vendorName) {
       this.inputDetailId = inputDetailId;
       this.inputId = inputId;
       this.productId = productId;
       this.productName = productName;
       this.price = price;
       this.quantity = quantity;
       this.unitId = unitId;
       this.inventoryId = inventoryId;
       this.totalMoney = totalMoney;
       this.vendorId = vendorId;
       this.vendorName = vendorName;
    }
   
    public int getInputDetailId() {
        return this.inputDetailId;
    }
    
    public void setInputDetailId(int inputDetailId) {
        this.inputDetailId = inputDetailId;
    }
    public Integer getInputId() {
        return this.inputId;
    }
    
    public void setInputId(Integer inputId) {
        this.inputId = inputId;
    }
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public Double getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Double quantity) {
        this.quantity = quantity;
    }
    public Integer getUnitId() {
        return this.unitId;
    }
    
    public void setUnitId(Integer unitId) {
        this.unitId = unitId;
    }
    public Integer getInventoryId() {
        return this.inventoryId;
    }
    
    public void setInventoryId(Integer inventoryId) {
        this.inventoryId = inventoryId;
    }
    public Double getTotalMoney() {
        return this.totalMoney;
    }
    
    public void setTotalMoney(Double totalMoney) {
        this.totalMoney = totalMoney;
    }
    public Integer getVendorId() {
        return this.vendorId;
    }
    
    public void setVendorId(Integer vendorId) {
        this.vendorId = vendorId;
    }
    public String getVendorName() {
        return this.vendorName;
    }
    
    public void setVendorName(String vendorName) {
        this.vendorName = vendorName;
    }




}


