package prototype.hibernate.datamodel.entities.output;
// Generated Oct 30, 2013 1:55:35 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Output generated by hbm2java
 */
public class Output  implements java.io.Serializable {


     private int outputId;
     private String outputName;
     private Date dateOutput;
     private Double totalMoney;
     private String userName;
     private String comment;
     private Integer fromInventoryId;
     private String fromInventoryName;
     private Integer toInventoryId;
     private String toInventoryName;
     private String userRequest;

    public Output() {
    }

	
    public Output(int outputId) {
        this.outputId = outputId;
    }
    public Output(int outputId, String outputName, Date dateOutput, Double totalMoney, String userName, String comment, Integer fromInventoryId, String fromInventoryName, Integer toInventoryId, String toInventoryName, String userRequest) {
       this.outputId = outputId;
       this.outputName = outputName;
       this.dateOutput = dateOutput;
       this.totalMoney = totalMoney;
       this.userName = userName;
       this.comment = comment;
       this.fromInventoryId = fromInventoryId;
       this.fromInventoryName = fromInventoryName;
       this.toInventoryId = toInventoryId;
       this.toInventoryName = toInventoryName;
       this.userRequest = userRequest;
    }
   
    public int getOutputId() {
        return this.outputId;
    }
    
    public void setOutputId(int outputId) {
        this.outputId = outputId;
    }
    public String getOutputName() {
        return this.outputName;
    }
    
    public void setOutputName(String outputName) {
        this.outputName = outputName;
    }
    public Date getDateOutput() {
        return this.dateOutput;
    }
    
    public void setDateOutput(Date dateOutput) {
        this.dateOutput = dateOutput;
    }
    public Double getTotalMoney() {
        return this.totalMoney;
    }
    
    public void setTotalMoney(Double totalMoney) {
        this.totalMoney = totalMoney;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Integer getFromInventoryId() {
        return this.fromInventoryId;
    }
    
    public void setFromInventoryId(Integer fromInventoryId) {
        this.fromInventoryId = fromInventoryId;
    }
    public String getFromInventoryName() {
        return this.fromInventoryName;
    }
    
    public void setFromInventoryName(String fromInventoryName) {
        this.fromInventoryName = fromInventoryName;
    }
    public Integer getToInventoryId() {
        return this.toInventoryId;
    }
    
    public void setToInventoryId(Integer toInventoryId) {
        this.toInventoryId = toInventoryId;
    }
    public String getToInventoryName() {
        return this.toInventoryName;
    }
    
    public void setToInventoryName(String toInventoryName) {
        this.toInventoryName = toInventoryName;
    }
    public String getUserRequest() {
        return this.userRequest;
    }
    
    public void setUserRequest(String userRequest) {
        this.userRequest = userRequest;
    }




}


