package prototype.hibernate.datamodel.entities.output;
// Generated Oct 30, 2013 1:55:35 PM by Hibernate Tools 3.6.0



/**
 * OutputDetail generated by hbm2java
 */
public class OutputDetail  implements java.io.Serializable {


     private int outputDetailId;
     private Integer outputId;
     private Integer productId;
     private String productName;
     private Double price;
     private Double quantity;
     private Integer unitId;
     private Double totalMoney;

    public OutputDetail() {
    }

	
    public OutputDetail(int outputDetailId) {
        this.outputDetailId = outputDetailId;
    }
    public OutputDetail(int outputDetailId, Integer outputId, Integer productId, String productName, Double price, Double quantity, Integer unitId, Double totalMoney) {
       this.outputDetailId = outputDetailId;
       this.outputId = outputId;
       this.productId = productId;
       this.productName = productName;
       this.price = price;
       this.quantity = quantity;
       this.unitId = unitId;
       this.totalMoney = totalMoney;
    }
   
    public int getOutputDetailId() {
        return this.outputDetailId;
    }
    
    public void setOutputDetailId(int outputDetailId) {
        this.outputDetailId = outputDetailId;
    }
    public Integer getOutputId() {
        return this.outputId;
    }
    
    public void setOutputId(Integer outputId) {
        this.outputId = outputId;
    }
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public Double getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Double quantity) {
        this.quantity = quantity;
    }
    public Integer getUnitId() {
        return this.unitId;
    }
    
    public void setUnitId(Integer unitId) {
        this.unitId = unitId;
    }
    public Double getTotalMoney() {
        return this.totalMoney;
    }
    
    public void setTotalMoney(Double totalMoney) {
        this.totalMoney = totalMoney;
    }




}


