package prototype.hibernate.datamodel.entities.vender;
// Generated Oct 30, 2013 1:55:35 PM by Hibernate Tools 3.6.0



/**
 * OrderVendorDetail generated by hbm2java
 */
public class OrderVendorDetail  implements java.io.Serializable {


     private int orderInventoryDetailId;
     private Integer orderVendorId;
     private Integer productId;
     private String productName;
     private Double price;
     private Integer unitId;
     private Double totalMoney;
     private Double quantity;

    public OrderVendorDetail() {
    }

	
    public OrderVendorDetail(int orderInventoryDetailId) {
        this.orderInventoryDetailId = orderInventoryDetailId;
    }
    public OrderVendorDetail(int orderInventoryDetailId, Integer orderVendorId, Integer productId, String productName, Double price, Integer unitId, Double totalMoney, Double quantity) {
       this.orderInventoryDetailId = orderInventoryDetailId;
       this.orderVendorId = orderVendorId;
       this.productId = productId;
       this.productName = productName;
       this.price = price;
       this.unitId = unitId;
       this.totalMoney = totalMoney;
       this.quantity = quantity;
    }
   
    public int getOrderInventoryDetailId() {
        return this.orderInventoryDetailId;
    }
    
    public void setOrderInventoryDetailId(int orderInventoryDetailId) {
        this.orderInventoryDetailId = orderInventoryDetailId;
    }
    public Integer getOrderVendorId() {
        return this.orderVendorId;
    }
    
    public void setOrderVendorId(Integer orderVendorId) {
        this.orderVendorId = orderVendorId;
    }
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public Integer getUnitId() {
        return this.unitId;
    }
    
    public void setUnitId(Integer unitId) {
        this.unitId = unitId;
    }
    public Double getTotalMoney() {
        return this.totalMoney;
    }
    
    public void setTotalMoney(Double totalMoney) {
        this.totalMoney = totalMoney;
    }
    public Double getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Double quantity) {
        this.quantity = quantity;
    }




}


