package prototype.hibernate.datamodel.entities.vender;
// Generated Oct 30, 2013 1:55:35 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * OrderVendor generated by hbm2java
 */
public class OrderVendor  implements java.io.Serializable {


     private int orderVendorId;
     private String orderVendorName;
     private String status;
     private Date orderDate;
     private String comment;
     private String userName;
     private String userRequest;

    public OrderVendor() {
    }

	
    public OrderVendor(int orderVendorId) {
        this.orderVendorId = orderVendorId;
    }
    public OrderVendor(int orderVendorId, String orderVendorName, String status, Date orderDate, String comment, String userName, String userRequest) {
       this.orderVendorId = orderVendorId;
       this.orderVendorName = orderVendorName;
       this.status = status;
       this.orderDate = orderDate;
       this.comment = comment;
       this.userName = userName;
       this.userRequest = userRequest;
    }
   
    public int getOrderVendorId() {
        return this.orderVendorId;
    }
    
    public void setOrderVendorId(int orderVendorId) {
        this.orderVendorId = orderVendorId;
    }
    public String getOrderVendorName() {
        return this.orderVendorName;
    }
    
    public void setOrderVendorName(String orderVendorName) {
        this.orderVendorName = orderVendorName;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getUserRequest() {
        return this.userRequest;
    }
    
    public void setUserRequest(String userRequest) {
        this.userRequest = userRequest;
    }




}


