package prototype.hibernate.datamodel.entities.vender;
// Generated Oct 30, 2013 1:55:35 PM by Hibernate Tools 3.6.0



/**
 * Vendor generated by hbm2java
 */
public class Vendor  implements java.io.Serializable {


     private int vendorId;
     private String vendorName;
     private String vendorAddress;
     private String vendorPhone;

    public Vendor() {
    }

	
    public Vendor(int vendorId) {
        this.vendorId = vendorId;
    }
    public Vendor(int vendorId, String vendorName, String vendorAddress, String vendorPhone) {
       this.vendorId = vendorId;
       this.vendorName = vendorName;
       this.vendorAddress = vendorAddress;
       this.vendorPhone = vendorPhone;
    }
   
    public int getVendorId() {
        return this.vendorId;
    }
    
    public void setVendorId(int vendorId) {
        this.vendorId = vendorId;
    }
    public String getVendorName() {
        return this.vendorName;
    }
    
    public void setVendorName(String vendorName) {
        this.vendorName = vendorName;
    }
    public String getVendorAddress() {
        return this.vendorAddress;
    }
    
    public void setVendorAddress(String vendorAddress) {
        this.vendorAddress = vendorAddress;
    }
    public String getVendorPhone() {
        return this.vendorPhone;
    }
    
    public void setVendorPhone(String vendorPhone) {
        this.vendorPhone = vendorPhone;
    }




}


