package prototype.hibernate.datamodel.entities.vender;
// Generated Oct 30, 2013 1:55:35 PM by Hibernate Tools 3.6.0



/**
 * VendorDetail generated by hbm2java
 */
public class VendorDetail  implements java.io.Serializable {


     private int vendorDetailId;
     private Integer vendorId;
     private Integer productId;
     private String productName;

    public VendorDetail() {
    }

	
    public VendorDetail(int vendorDetailId) {
        this.vendorDetailId = vendorDetailId;
    }
    public VendorDetail(int vendorDetailId, Integer vendorId, Integer productId, String productName) {
       this.vendorDetailId = vendorDetailId;
       this.vendorId = vendorId;
       this.productId = productId;
       this.productName = productName;
    }
   
    public int getVendorDetailId() {
        return this.vendorDetailId;
    }
    
    public void setVendorDetailId(int vendorDetailId) {
        this.vendorDetailId = vendorDetailId;
    }
    public Integer getVendorId() {
        return this.vendorId;
    }
    
    public void setVendorId(Integer vendorId) {
        this.vendorId = vendorId;
    }
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }




}


